package com.starline.subscriptions.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;
import org.hibernate.annotations.Comment;

import java.time.LocalDateTime;

@Entity
@Table(name = "PAYMENT_HISTORY")
@Setter
@Getter
@Accessors(chain = true)
public class PaymentHistory extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "PAYMENT_HISTORY_SEQ")
    @SequenceGenerator(name = "PAYMENT_HISTORY_SEQ", sequenceName = "PAYMENT_HISTORY_SEQ", allocationSize = 1)
    @Column(name = "ID")
    private Long id;

    @Column(name = "PAYMENT_TYPE", length = 50)
    @Comment(value = "Payment Type", on = "PAYMENT_TYPE")
    private String paymentType;


    @Column(name = "PAYMENT_STATUS", length = 50)
    @Comment(value = "Payment Status", on = "PAYMENT_STATUS")
    private String paymentStatus;

    @Column(name = "STATUS_CODE", length = 50)
    @Comment(value = "Status Code", on = "STATUS_CODE")
    private String statusCode;

    @Column(name = "AMOUNT")
    @Comment(value = "Amount", on = "AMOUNT")
    private String amount;

    @Column(name = "PARTNER_TRX_ID")
    @Comment(value = "Transaction ID generated by payment gateway for reference", on = "PARTNER_TRX_ID")
    private String partnerTrxId;


    @Column(name = "PAYMENT_DATE")
    @Comment(value = "Date when payment was successful", on = "PAYMENT_DATE")
    private LocalDateTime paymentDate;

    @Column(name = "REFERENCE_ID", length = 50)
    @Comment(value = "Reference Id to refer another entity that this payment is associated (e.g. subscription_id)", on = "REFERENCE_ID")
    private String referenceId;

    @Column(name = "PAYMENT_URL", length = 1000)
    @Comment(value = "Payment URL", on = "PAYMENT_URL")
    private String paymentUrl;

    @Column(name = "REASON")
    @Comment(value = "Reason for payment failure, cancellation, etc.", on = "REASON")
    private String reason;
}
